CREATE TABLE events (
_id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
name VARCHAR(25),
location VARCHAR(25),
date_start TIMESTAMP NOT NULL,
date_end TIMESTAMP NOT NULL,
_date_insert TIMESTAMP NOT NULL,
state VARCHAR(30),
PRIMARY KEY(_id)
);
